#!/bin/sh

BUILD_ROOT=$1

if [ -z $BUILD_ROOT ] ; then
    exit 1
fi

rm -rf $BUILD_ROOT

mkdir -p "$BUILD_ROOT/usr/share/doc/certification-docs"

make
cp -a "MAAS_Advanced_Network_Installation_And_Configuration_Scripted.pdf" "$BUILD_ROOT/usr/share/doc/certification-docs/"
cp -a "MAAS_Advanced_Network_Installation_And_Configuration_Scripted.html" "$BUILD_ROOT/usr/share/doc/certification-docs/"
cp -a "Self-Test_Guide.pdf" "$BUILD_ROOT/usr/share/doc/certification-docs/"
cp -a "Self-Test_Guide.html" "$BUILD_ROOT/usr/share/doc/certification-docs/"
cp -a "images" "$BUILD_ROOT/usr/share/doc/certification-docs/"
